version: "3.8"

x-logging: &default-logging
  driver: "json-file"
  options:
    max-size: "10m"
    max-file: "5"

services:
  postgres:
    image: postgres:16-alpine
    container_name: aluon-saas-postgres-dev2
    environment:
      POSTGRES_DB: aluonbbdd
      POSTGRES_USER: aluon
      POSTGRES_PASSWORD: aluon
    ports:
      - "3000:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - aluon-network
    restart: unless-stopped
    logging: *default-logging

  backend:
    image: docker.io/r0dr1g0m0r3n0/aluon-saas-backend:dev2
    container_name: aluon-saas-backend-dev2
    environment:
      - SPRING_PROFILES_ACTIVE=dev2
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/aluonbbdd
      - SPRING_DATASOURCE_USERNAME=aluon
      - SPRING_DATASOURCE_PASSWORD=aluon
      - APP_CORS_ALLOWED_ORIGINS=${APP_CORS_ALLOWED_ORIGINS}
      - SPRING_MAIL_HOST=${SPRING_MAIL_HOST}
      - SPRING_MAIL_PORT=${SPRING_MAIL_PORT}
      - SPRING_MAIL_USERNAME=${SPRING_MAIL_USERNAME}
      - SPRING_MAIL_PASSWORD=${SPRING_MAIL_PASSWORD}
      - SPRING_MAIL_FROM=${SPRING_MAIL_FROM}
      - SPRING_MAIL_PROPERTIES_MAIL_SMTP_AUTH=${SPRING_MAIL_PROPERTIES_MAIL_SMTP_AUTH}
      - SPRING_MAIL_PROPERTIES_MAIL_SMTP_STARTTLS_ENABLE=${SPRING_MAIL_PROPERTIES_MAIL_SMTP_STARTTLS_ENABLE}
      - JIRA_ENABLED=${JIRA_ENABLED}
      - JIRA_BASE_URL=${JIRA_BASE_URL}
      - JIRA_URL=${JIRA_URL}
      - JIRA_USERNAME=${JIRA_USERNAME}
      - JIRA_API_TOKEN=${JIRA_API_TOKEN}
      - JIRA_PROJECT_KEY=${JIRA_PROJECT_KEY}
      - JIRA_ISSUE_TYPE_NAME=${JIRA_ISSUE_TYPE_NAME}
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    networks:
      - aluon-network
    restart: unless-stopped
    logging: *default-logging

  frontend:
    image: docker.io/r0dr1g0m0r3n0/aluon-saas-frontend:dev2
    container_name: aluon-saas-frontend-dev2
    ports:
      - "5173:80"
    networks:
      - aluon-network
    restart: unless-stopped
    logging: *default-logging

networks:
  aluon-network:
    driver: bridge

volumes:
  pgdata:
    name: aluon-pgdata-dev2
