version: "3.8"

x-logging: &default-logging
  driver: "json-file"
  options:
    max-size: "10m"
    max-file: "5"

services:
  backend:
    image: docker.io/r0dr1g0m0r3n0/aluon-backend:preprod
    container_name: aluon-backend-preprod
    environment:
      - SPRING_PROFILES_ACTIVE=preprod
      - SPRING_DATASOURCE_URL=jdbc:postgresql://192.168.99.14:3000/aluonbbddpreprod
      - SPRING_DATASOURCE_USERNAME=aluon
      - SPRING_DATASOURCE_PASSWORD=aluon
    ports:
      - "8081:8080"
    networks:
      - aluon-network
    restart: unless-stopped
    logging: *default-logging

  frontend:
    image: docker.io/r0dr1g0m0r3n0/aluon-frontend:preprod
    container_name: aluon-frontend-preprod
    ports:
      - "5174:80"
    networks:
      - aluon-network
    restart: unless-stopped
    logging: *default-logging

networks:
  aluon-network:
    driver: bridge


