ALTER TABLE cutlists
  ADD COLUMN IF NOT EXISTS distributor VARCHAR(120),
  ADD COLUMN IF NOT EXISTS budget_number VARCHAR(50),
  ADD COLUMN IF NOT EXISTS budget_date DATE,
  ADD COLUMN IF NOT EXISTS color VARCHAR(80),
  ADD COLUMN IF NOT EXISTS hinges_side VARCHAR(10),
  ADD COLUMN IF NOT EXISTS porter_automatic BOOLEAN,
  ADD COLUMN IF NOT EXISTS automation_included BOOLEAN,
  ADD COLUMN IF NOT EXISTS opening_side VARCHAR(10);
