ALTER TABLE cutlists
  ADD COLUMN IF NOT EXISTS installer_name VARCHAR(120),
  ADD COLUMN IF NOT EXISTS height_left_mm INTEGER,
  ADD COLUMN IF NOT EXISTS height_right_mm INTEGER,
  ADD COLUMN IF NOT EXISTS width_left_mm INTEGER,
  ADD COLUMN IF NOT EXISTS width_right_mm INTEGER;
