spring:
  mail:
    host: ${SPRING_MAIL_HOST:smtp.gmail.com}
    port: ${SPRING_MAIL_PORT:587}
    username: ${SPRING_MAIL_USERNAME:}
    password: ${SPRING_MAIL_PASSWORD:}
    from: ${SPRING_MAIL_FROM:}
    properties:
      mail:
        smtp:
          auth: ${SPRING_MAIL_PROPERTIES_MAIL_SMTP_AUTH:true}
          starttls:
            enable: ${SPRING_MAIL_PROPERTIES_MAIL_SMTP_STARTTLS_ENABLE:true}
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://postgres:5432/aluonbbdd}
    username: ${SPRING_DATASOURCE_USERNAME:aluon}
    password: ${SPRING_DATASOURCE_PASSWORD:aluon}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        tenant_identifier_resolver: com.aluon.core.tenant.service.CurrentTenantIdentifierResolverImpl
  modulith:
    events:
      jdbc-schema-initialization:
        enabled: true

app:
  cors:
    allowed-origins: ${APP_CORS_ALLOWED_ORIGINS:https://app-aluon-unqc.vercel.app,https://aluondev.iconseriespeliculas.xyz}
