spring:
  application:
    name: "aluon-saas-backend"
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:local}
  servlet:
    multipart:
      enabled: true
      max-file-size: ${SPRING_SERVLET_MULTIPART_MAX_FILE_SIZE:25MB}
      max-request-size: ${SPRING_SERVLET_MULTIPART_MAX_REQUEST_SIZE:25MB}

app:
  tenant:
    default-id: ${APP_TENANT_DEFAULT_ID:}
