spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://192.168.99.14:3000/aluonbbdd}
    driver-class-name: ${SPRING_DATASOURCE_DRIVER:org.postgresql.Driver}
    username: ${SPRING_DATASOURCE_USERNAME:aluon}
    password: ${SPRING_DATASOURCE_PASSWORD:aluon}
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        tenant_identifier_resolver: com.aluon.core.tenant.CurrentTenantIdentifierResolverImpl
  modulith:
    events:
      jdbc-schema-initialization:
        enabled: true
