import type { Customer } from '../../../hooks/useCustomers';
import type { WorkOrderData } from '../models';
import type { UseBudgetWorkflowResult } from './useBudgetWorkflow';
import type { UseCutlistWorkflowResult } from './useCutlistWorkflow';
import type { UseWorkOrderBaseStateResult } from './useWorkOrderBaseState';
import type { UseWorkflowProgressResult } from './useWorkflowProgress';
import type { UseWorkOrderPrintingResult } from './useWorkOrderPrinting';

type BuildWorkOrdersResultParams = {
  customers: Customer[];
  base: UseWorkOrderBaseStateResult;
  budget: UseBudgetWorkflowResult;
  cutlist: UseCutlistWorkflowResult;
  workflow: UseWorkflowProgressResult;
  selectedModel: { id: string; label: string; pricePerM2: number };
  hasModelRef: boolean;
  canGenerateDevelopment: boolean;
  workOrderData: WorkOrderData;
  printing: UseWorkOrderPrintingResult;
  applyRequest: (req: UseWorkOrderBaseStateResult['requests'][number]) => void;
  createRequest: (data: { customerName: string; modelId: string; m2: number; reference: string; googleView: boolean; notes: string }) => void;
  deleteRequest: (req: UseWorkOrderBaseStateResult['requests'][number]) => Promise<void>;
  resetDownstream: (options?: { keepBudget?: boolean }) => void;
};

export const buildWorkOrdersResult = ({
  customers,
  base,
  budget,
  cutlist,
  workflow,
  selectedModel,
  hasModelRef,
  canGenerateDevelopment,
  workOrderData,
  printing,
  applyRequest,
  createRequest,
  deleteRequest,
  resetDownstream,
}: BuildWorkOrdersResultParams) => ({
  customers,
  requests: base.requests,
  customerId: base.customerId,
  modelId: base.modelId,
  modelReference: base.modelReference,
  modelImage: base.modelImage,
  m2: base.m2,
  googleView: base.googleView,
  notes: base.notes,
  budgetGenerated: budget.budgetGenerated,
  accountingApproved: budget.accountingApproved,
  adminApproved: budget.adminApproved,
  approverUserId: budget.approverUserId,
  developmentGenerated: base.developmentGenerated,
  cutlistGenerated: cutlist.cutlistGenerated,
  doorType: cutlist.doorType,
  doorModel: cutlist.doorModel,
  widthMm: cutlist.widthMm,
  heightMm: cutlist.heightMm,
  groundClearanceMm: cutlist.groundClearanceMm,
  largueroMm: cutlist.largueroMm,
  topFrame: cutlist.topFrame,
  hingesSide: cutlist.hingesSide,
  porterAutomatic: cutlist.porterAutomatic,
  automationIncluded: cutlist.automationIncluded,
  automationReinforcement: cutlist.automationReinforcement,
  openingSide: cutlist.openingSide,
  railType: cutlist.railType,
  mountingType: cutlist.mountingType,
  tail: cutlist.tail,
  cutlistResult: cutlist.cutlistResult,
  cutlistError: cutlist.cutlistError,
  cutlistLoading: cutlist.cutlistLoading,
  cutlistImageIndex: cutlist.cutlistImageIndex,
  cutlistHoverIndex: cutlist.cutlistHoverIndex,
  cutlistPinnedIndex: cutlist.cutlistPinnedIndex,
  cutlistDistributor: cutlist.cutlistDistributor,
  cutlistBudgetNumber: cutlist.cutlistBudgetNumber,
  cutlistBudgetDate: cutlist.cutlistBudgetDate,
  cutlistColor: cutlist.cutlistColor,
  installerName: cutlist.installerName,
  heightLeftMm: cutlist.heightLeftMm,
  heightRightMm: cutlist.heightRightMm,
  widthLeftMm: cutlist.widthLeftMm,
  widthRightMm: cutlist.widthRightMm,
  prodCut: base.prodCut,
  prodFab: base.prodFab,
  prodLac: base.prodLac,
  prodLacControl: base.prodLacControl,
  finalized: base.finalized,
  ready: base.ready,
  selectedRequestId: base.selectedRequestId,
  tab: base.tab,
  showBudgetModal: budget.showBudgetModal,
  showRequestModal: base.showRequestModal,
  showWorkOrderModal: base.showWorkOrderModal,
  selectedModel,
  hasModelRef,
  canGenerateBudget: budget.canGenerateBudget,
  budget: budget.budget,
  productionPct: workflow.productionPct,
  overallPct: workflow.overallPct,
  canGenerateDevelopment,
  needsGroundClearance: cutlist.needsGroundClearance,
  needsLarguero: cutlist.needsLarguero,
  needsTopFrame: cutlist.needsTopFrame,
  needsAutomation: cutlist.needsAutomation,
  needsHingesSide: cutlist.needsHingesSide,
  needsPorterAutomatic: cutlist.needsPorterAutomatic,
  needsOpeningSide: cutlist.needsOpeningSide,
  needsLeftRightHeights: cutlist.needsLeftRightHeights,
  needsLeftRightWidths: cutlist.needsLeftRightWidths,
  needsRail: cutlist.needsRail,
  needsMounting: cutlist.needsMounting,
  needsTail: cutlist.needsTail,
  cutlistImages: cutlist.cutlistImages,
  activeCutlistIndex: cutlist.activeCutlistIndex,
  cutlistBlockingReasons: cutlist.cutlistBlockingReasons,
  canGenerateCutlist: cutlist.canGenerateCutlist,
  canStartProduction: workflow.canStartProduction,
  canFinalize: workflow.canFinalize,
  pipelineSteps: workflow.pipelineSteps,
  budgetData: budget.budgetData,
  pendingBudgets: budget.pendingBudgets,
  budgetValidationError: budget.budgetValidationError,
  setBudgetValidationError: budget.setBudgetValidationError,
  workOrderData,
  setRequests: base.setRequests,
  setCustomerId: base.setCustomerId,
  setModelId: base.setModelId,
  setModelReference: base.setModelReference,
  setModelImage: base.setModelImage,
  setM2: base.setM2,
  setGoogleView: base.setGoogleView,
  setNotes: base.setNotes,
  setBudgetGenerated: budget.setBudgetGenerated,
  setDevelopmentGenerated: base.setDevelopmentGenerated,
  setCutlistGenerated: cutlist.setCutlistGenerated,
  setDoorType: cutlist.setDoorType,
  setDoorModel: cutlist.setDoorModel,
  setWidthMm: cutlist.setWidthMm,
  setHeightMm: cutlist.setHeightMm,
  setGroundClearanceMm: cutlist.setGroundClearanceMm,
  setLargueroMm: cutlist.setLargueroMm,
  setTopFrame: cutlist.setTopFrame,
  setHingesSide: cutlist.setHingesSide,
  setPorterAutomatic: cutlist.setPorterAutomatic,
  setAutomationIncluded: cutlist.setAutomationIncluded,
  setAutomationReinforcement: cutlist.setAutomationReinforcement,
  setOpeningSide: cutlist.setOpeningSide,
  setRailType: cutlist.setRailType,
  setMountingType: cutlist.setMountingType,
  setTail: cutlist.setTail,
  setCutlistResult: cutlist.setCutlistResult,
  setCutlistError: cutlist.setCutlistError,
  setCutlistLoading: cutlist.setCutlistLoading,
  setCutlistImageIndex: cutlist.setCutlistImageIndex,
  setCutlistHoverIndex: cutlist.setCutlistHoverIndex,
  setCutlistPinnedIndex: cutlist.setCutlistPinnedIndex,
  setCutlistDistributor: cutlist.setCutlistDistributor,
  setCutlistBudgetNumber: cutlist.setCutlistBudgetNumber,
  setCutlistBudgetDate: cutlist.setCutlistBudgetDate,
  setCutlistColor: cutlist.setCutlistColor,
  setInstallerName: cutlist.setInstallerName,
  setHeightLeftMm: cutlist.setHeightLeftMm,
  setHeightRightMm: cutlist.setHeightRightMm,
  setWidthLeftMm: cutlist.setWidthLeftMm,
  setWidthRightMm: cutlist.setWidthRightMm,
  setProdCut: base.setProdCut,
  setProdFab: base.setProdFab,
  setProdLac: base.setProdLac,
  setProdLacControl: base.setProdLacControl,
  setFinalized: base.setFinalized,
  setReady: base.setReady,
  setSelectedRequestId: base.setSelectedRequestId,
  setTab: base.setTab,
  setShowBudgetModal: budget.setShowBudgetModal,
  setShowRequestModal: base.setShowRequestModal,
  setShowWorkOrderModal: base.setShowWorkOrderModal,
  resetDownstream,
  handleGenerateBudget: budget.handleGenerateBudget,
  handleToggleAccounting: budget.handleToggleAccounting,
  handleApproverUserIdChange: budget.handleApproverUserIdChange,
  handleApproveBudget: budget.handleApproveBudget,
  handleGenerateCutlist: cutlist.handleGenerateCutlist,
  handleCutlistFormPrint: printing.handleCutlistFormPrint,
  clearCutlist: cutlist.clearCutlist,
  applyRequest,
  createRequest,
  deleteRequest,
  handlePrint: printing.handlePrint,
  handleEmail: printing.handleEmail,
  handleWorkOrderPrint: printing.handleWorkOrderPrint,
});
